# Generated by Django 2.1.2 on 2018-12-26 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='note',
            options={'ordering': ['-date_posted']},
        ),
    ]
