# Generated by Django 2.1.2 on 2018-12-27 07:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_note_color'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='color',
            new_name='tag',
        ),
    ]
