# Generated by Django 2.1.2 on 2019-01-11 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rollno', models.CharField(max_length=9)),
                ('branch', models.CharField(choices=[('CSE', 'Computer Science'), ('EE', 'Electrical Engineering'), ('ME', 'Mechanical Engineering')], default='CSE', max_length=3)),
                ('employment', models.CharField(choices=[('TA', 'Teaching Assistant'), ('ST', 'Student'), ('PR', 'Professor')], default='ST', max_length=2)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
