# Generated by Django 2.1.2 on 2019-01-11 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190112_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='tag',
            field=models.CharField(choices=[('primary', 'Blue'), ('secondary', 'Grey'), ('success', 'Green'), ('danger', 'Red'), ('warning', 'Yellow'), ('info', 'Light-Blue'), ('light', 'White'), ('dark', 'Dark-Grey')], default='info', max_length=10),
        ),
    ]
