# Generated by Django 2.1.2 on 2019-01-11 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_profile_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='tag',
        ),
    ]
